import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./components/Nav";
import Head from "next/head";
import { Providers } from "./GlobalRedux/provider";
const inter = Inter({ subsets: ["latin"] });
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};

export default function RootLayout({ children }) {
  const router = useRouter();

  // List of routes where you want to hide the navigation
  const routesWithoutNavigation = ['/login', '/signup', '/profile-data-input'];

  const shouldRenderNavigation = !routesWithoutNavigation.includes(router.pathname);
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
      </Head>
      <body className={inter.className}>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
