import './globals.css'
import { Inter } from 'next/font/google'
import Nav from "./components/Nav"
import Head from "next/head"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
        />
      </Head>
      <body className={inter.className}>
      <Nav/>
        {children}
        </body>
    </html>
  )
}
